# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Patrick\Documents\maya\2014-x64\scripts\FluidExplorerPlugin\ui\Resources\CreateProjectDialogUI.ui'
#
# Created: Thu Jul 13 11:29:47 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_CreateProjectDialog(object):
    def setupUi(self, CreateProjectDialog):
        CreateProjectDialog.setObjectName("CreateProjectDialog")
        CreateProjectDialog.resize(640, 670)
        CreateProjectDialog.setMinimumSize(QtCore.QSize(640, 670))
        CreateProjectDialog.setMaximumSize(QtCore.QSize(640, 670))
        self.pushButtonNewPrjHelp = QtWidgets.QPushButton(CreateProjectDialog)
        self.pushButtonNewPrjHelp.setGeometry(QtCore.QRect(580, 16, 40, 40))
        self.pushButtonNewPrjHelp.setStyleSheet("")
        self.pushButtonNewPrjHelp.setText("")
        self.pushButtonNewPrjHelp.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonNewPrjHelp.setObjectName("pushButtonNewPrjHelp")
        self.labelMain = QtWidgets.QLabel(CreateProjectDialog)
        self.labelMain.setGeometry(QtCore.QRect(21, 20, 211, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setItalic(False)
        font.setStrikeOut(False)
        self.labelMain.setFont(font)
        self.labelMain.setObjectName("labelMain")
        self.lineEdit_SimulationName = QtWidgets.QLineEdit(CreateProjectDialog)
        self.lineEdit_SimulationName.setGeometry(QtCore.QRect(20, 100, 600, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_SimulationName.setFont(font)
        self.lineEdit_SimulationName.setObjectName("lineEdit_SimulationName")
        self.label_Name = QtWidgets.QLabel(CreateProjectDialog)
        self.label_Name.setGeometry(QtCore.QRect(20, 80, 170, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName("label_Name")
        self.label_Location = QtWidgets.QLabel(CreateProjectDialog)
        self.label_Location.setGeometry(QtCore.QRect(20, 140, 170, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Location.setFont(font)
        self.label_Location.setObjectName("label_Location")
        self.lineEdit_ProjPath = QtWidgets.QLineEdit(CreateProjectDialog)
        self.lineEdit_ProjPath.setGeometry(QtCore.QRect(20, 160, 521, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ProjPath.setFont(font)
        self.lineEdit_ProjPath.setObjectName("lineEdit_ProjPath")
        self.pushButtonBrowse = QtWidgets.QPushButton(CreateProjectDialog)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(550, 160, 71, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonBrowse.setFont(font)
        self.pushButtonBrowse.setStyleSheet("")
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.tabWidget = QtWidgets.QTabWidget(CreateProjectDialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(20, 210, 601, 381))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tabSampling = QtWidgets.QWidget()
        self.tabSampling.setObjectName("tabSampling")
        self.groupBoxCameras = QtWidgets.QGroupBox(self.tabSampling)
        self.groupBoxCameras.setGeometry(QtCore.QRect(20, 19, 554, 190))
        self.groupBoxCameras.setObjectName("groupBoxCameras")
        self.pushButton_CamPV = QtWidgets.QPushButton(self.groupBoxCameras)
        self.pushButton_CamPV.setGeometry(QtCore.QRect(33, 46, 100, 100))
        self.pushButton_CamPV.setText("")
        self.pushButton_CamPV.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_CamPV.setObjectName("pushButton_CamPV")
        self.pushButton_CamVC = QtWidgets.QPushButton(self.groupBoxCameras)
        self.pushButton_CamVC.setGeometry(QtCore.QRect(163, 46, 100, 100))
        self.pushButton_CamVC.setText("")
        self.pushButton_CamVC.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_CamVC.setObjectName("pushButton_CamVC")
        self.pushButton_CamSPH = QtWidgets.QPushButton(self.groupBoxCameras)
        self.pushButton_CamSPH.setGeometry(QtCore.QRect(293, 46, 100, 100))
        self.pushButton_CamSPH.setText("")
        self.pushButton_CamSPH.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_CamSPH.setObjectName("pushButton_CamSPH")
        self.pushButton_ROT = QtWidgets.QPushButton(self.groupBoxCameras)
        self.pushButton_ROT.setGeometry(QtCore.QRect(423, 46, 100, 100))
        self.pushButton_ROT.setText("")
        self.pushButton_ROT.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_ROT.setObjectName("pushButton_ROT")
        self.spinBox_rotDeg = QtWidgets.QSpinBox(self.groupBoxCameras)
        self.spinBox_rotDeg.setGeometry(QtCore.QRect(425, 156, 61, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_rotDeg.setFont(font)
        self.spinBox_rotDeg.setMinimum(10)
        self.spinBox_rotDeg.setMaximum(90)
        self.spinBox_rotDeg.setProperty("value", 45)
        self.spinBox_rotDeg.setObjectName("spinBox_rotDeg")
        self.label = QtWidgets.QLabel(self.groupBoxCameras)
        self.label.setGeometry(QtCore.QRect(495, 156, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBoxCameras)
        self.label_2.setGeometry(QtCore.QRect(33, 23, 101, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBoxCameras)
        self.label_3.setGeometry(QtCore.QRect(162, 23, 101, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBoxCameras)
        self.label_4.setGeometry(QtCore.QRect(293, 23, 101, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBoxCameras)
        self.label_5.setGeometry(QtCore.QRect(423, 23, 101, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_selectedCam = QtWidgets.QLabel(self.groupBoxCameras)
        self.label_selectedCam.setGeometry(QtCore.QRect(284, 156, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_selectedCam.setFont(font)
        self.label_selectedCam.setText("")
        self.label_selectedCam.setAlignment(QtCore.Qt.AlignCenter)
        self.label_selectedCam.setObjectName("label_selectedCam")
        self.labelNumberSeq = QtWidgets.QLabel(self.tabSampling)
        self.labelNumberSeq.setGeometry(QtCore.QRect(20, 260, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelNumberSeq.setFont(font)
        self.labelNumberSeq.setObjectName("labelNumberSeq")
        self.labelTime = QtWidgets.QLabel(self.tabSampling)
        self.labelTime.setGeometry(QtCore.QRect(20, 320, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelTime.setFont(font)
        self.labelTime.setObjectName("labelTime")
        self.horizontalSlider_numberSeq = QtWidgets.QSlider(self.tabSampling)
        self.horizontalSlider_numberSeq.setGeometry(QtCore.QRect(285, 261, 288, 20))
        self.horizontalSlider_numberSeq.setStyleSheet(" QSlider::groove:horizontal {\n"
"     border: 1px solid #999999;\n"
"     height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"     background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"     margin: 2px 0;\n"
" }\n"
"\n"
" QSlider::handle:horizontal {\n"
"     background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"     border: 1px solid #5c5c5c;\n"
"     width: 18px;\n"
"     margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"     border-radius: 3px;\n"
" }\n"
"\n"
"QSlider::sub-page:qlineargradient {\n"
"     border: 1px solid #999999;\n"
"     height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"     background: rgb(255, 160, 47);\n"
"     margin: 2px 0;\n"
"}")
        self.horizontalSlider_numberSeq.setMinimum(1)
        self.horizontalSlider_numberSeq.setMaximum(500)
        self.horizontalSlider_numberSeq.setPageStep(1)
        self.horizontalSlider_numberSeq.setProperty("value", 128)
        self.horizontalSlider_numberSeq.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_numberSeq.setObjectName("horizontalSlider_numberSeq")
        self.lineEdit_numberSeq = QtWidgets.QLineEdit(self.tabSampling)
        self.lineEdit_numberSeq.setGeometry(QtCore.QRect(202, 259, 65, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_numberSeq.setFont(font)
        self.lineEdit_numberSeq.setObjectName("lineEdit_numberSeq")
        self.labelAnimationTime = QtWidgets.QLabel(self.tabSampling)
        self.labelAnimationTime.setGeometry(QtCore.QRect(20, 290, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelAnimationTime.setFont(font)
        self.labelAnimationTime.setObjectName("labelAnimationTime")
        self.labelAnimationTimeStartEnd = QtWidgets.QLabel(self.tabSampling)
        self.labelAnimationTimeStartEnd.setGeometry(QtCore.QRect(285, 290, 281, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelAnimationTimeStartEnd.setFont(font)
        self.labelAnimationTimeStartEnd.setObjectName("labelAnimationTimeStartEnd")
        self.labelFluidBox = QtWidgets.QLabel(self.tabSampling)
        self.labelFluidBox.setGeometry(QtCore.QRect(20, 230, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelFluidBox.setFont(font)
        self.labelFluidBox.setObjectName("labelFluidBox")
        self.pushButtonBrowse_CalculateTime = QtWidgets.QPushButton(self.tabSampling)
        self.pushButtonBrowse_CalculateTime.setGeometry(QtCore.QRect(460, 320, 113, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonBrowse_CalculateTime.setFont(font)
        self.pushButtonBrowse_CalculateTime.setStyleSheet("")
        self.pushButtonBrowse_CalculateTime.setObjectName("pushButtonBrowse_CalculateTime")
        self.labelFluidBox_Value = QtWidgets.QLabel(self.tabSampling)
        self.labelFluidBox_Value.setGeometry(QtCore.QRect(119, 230, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelFluidBox_Value.setFont(font)
        self.labelFluidBox_Value.setText("")
        self.labelFluidBox_Value.setObjectName("labelFluidBox_Value")
        self.labelTime_Value = QtWidgets.QLabel(self.tabSampling)
        self.labelTime_Value.setGeometry(QtCore.QRect(72, 320, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.labelTime_Value.setFont(font)
        self.labelTime_Value.setObjectName("labelTime_Value")
        self.tabWidget.addTab(self.tabSampling, "")
        self.tabParameters = QtWidgets.QWidget()
        self.tabParameters.setEnabled(True)
        self.tabParameters.setObjectName("tabParameters")
        self.scrollArea = QtWidgets.QScrollArea(self.tabParameters)
        self.scrollArea.setGeometry(QtCore.QRect(10, 10, 561, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 559, 309))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 581, 311))
        self.widget.setObjectName("widget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tabParameters, "")
        self.pushButtonCreateSimulation = QtWidgets.QPushButton(CreateProjectDialog)
        self.pushButtonCreateSimulation.setGeometry(QtCore.QRect(20, 610, 601, 40))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pushButtonCreateSimulation.setFont(font)
        self.pushButtonCreateSimulation.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/ico_search.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCreateSimulation.setIcon(icon)
        self.pushButtonCreateSimulation.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonCreateSimulation.setObjectName("pushButtonCreateSimulation")

        self.retranslateUi(CreateProjectDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CreateProjectDialog)

    def retranslateUi(self, CreateProjectDialog):
        CreateProjectDialog.setWindowTitle(QtCore.QCoreApplication.translate("CreateProjectDialog", "Fluid Explorer - Create Simulation", None))
        self.labelMain.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Create Simulation", None))
        self.label_Name.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Simulation Name:", None))
        self.label_Location.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Location:", None))
        self.pushButtonBrowse.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Browse ...", None))
        self.groupBoxCameras.setTitle(QtCore.QCoreApplication.translate("CreateProjectDialog", "Select one or more Cameras", None))
        self.label.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "deg.", None))
        self.label_2.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Perspective", None))
        self.label_3.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "View Cube", None))
        self.label_4.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Custom", None))
        self.label_5.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Rotation", None))
        self.labelNumberSeq.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Number of Simulations:", None))
        self.labelTime.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Time:", None))
        self.lineEdit_numberSeq.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "128", None))
        self.labelAnimationTime.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Animation [Start Time / End Time]:", None))
        self.labelAnimationTimeStartEnd.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "1.00 / 50.00", None))
        self.labelFluidBox.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Fluid Shape:", None))
        self.pushButtonBrowse_CalculateTime.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Calculate Time ...", None))
        self.labelTime_Value.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "-:-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSampling), QtCore.QCoreApplication.translate("CreateProjectDialog", "Sampling", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameters), QtCore.QCoreApplication.translate("CreateProjectDialog", "Parameters", None))
        self.pushButtonCreateSimulation.setText(QtCore.QCoreApplication.translate("CreateProjectDialog", "Start Simulation", None))

