# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Patrick\Documents\maya\2014-x64\scripts\FluidExplorerPlugin\ui\Resources\DetailsViewUI.ui'
#
# Created: Fri Jan 27 11:46:27 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ProjectDetailsView(object):
    def setupUi(self, ProjectDetailsView):
        ProjectDetailsView.setObjectName("ProjectDetailsView")
        ProjectDetailsView.resize(340, 629)
        self.label_projectName = QtGui.QLabel(ProjectDetailsView)
        self.label_projectName.setGeometry(QtCore.QRect(20, 48, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.label_projectName.setFont(font)
        self.label_projectName.setObjectName("label_projectName")
        self.lineEdit_projectName = QtGui.QLineEdit(ProjectDetailsView)
        self.lineEdit_projectName.setGeometry(QtCore.QRect(20, 70, 301, 20))
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")
        self.pushButton_applyCache = QtGui.QPushButton(ProjectDetailsView)
        self.pushButton_applyCache.setGeometry(QtCore.QRect(230, 282, 91, 23))
        self.pushButton_applyCache.setObjectName("pushButton_applyCache")
        self.comboBox_simulations = QtGui.QComboBox(ProjectDetailsView)
        self.comboBox_simulations.setGeometry(QtCore.QRect(20, 283, 191, 21))
        self.comboBox_simulations.setObjectName("comboBox_simulations")
        self.line_1 = QtGui.QFrame(ProjectDetailsView)
        self.line_1.setGeometry(QtCore.QRect(20, 39, 300, 1))
        self.line_1.setMinimumSize(QtCore.QSize(0, 1))
        self.line_1.setStyleSheet("")
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.label_detailsView = QtGui.QLabel(ProjectDetailsView)
        self.label_detailsView.setGeometry(QtCore.QRect(20, 8, 271, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_detailsView.setFont(font)
        self.label_detailsView.setStyleSheet("")
        self.label_detailsView.setObjectName("label_detailsView")
        self.checkBox_showPreview = QtGui.QCheckBox(ProjectDetailsView)
        self.checkBox_showPreview.setGeometry(QtCore.QRect(20, 253, 121, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_showPreview.setFont(font)
        self.checkBox_showPreview.setObjectName("checkBox_showPreview")
        self.lineEdit_projectPath = QtGui.QLineEdit(ProjectDetailsView)
        self.lineEdit_projectPath.setGeometry(QtCore.QRect(20, 120, 300, 20))
        self.lineEdit_projectPath.setObjectName("lineEdit_projectPath")
        self.label_projectPath = QtGui.QLabel(ProjectDetailsView)
        self.label_projectPath.setGeometry(QtCore.QRect(20, 99, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_projectPath.setFont(font)
        self.label_projectPath.setObjectName("label_projectPath")
        self.label_fluidContainer = QtGui.QLabel(ProjectDetailsView)
        self.label_fluidContainer.setGeometry(QtCore.QRect(20, 148, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fluidContainer.setFont(font)
        self.label_fluidContainer.setObjectName("label_fluidContainer")
        self.lineEdit_fluidContainer = QtGui.QLineEdit(ProjectDetailsView)
        self.lineEdit_fluidContainer.setGeometry(QtCore.QRect(20, 169, 121, 20))
        self.lineEdit_fluidContainer.setStyleSheet("")
        self.lineEdit_fluidContainer.setObjectName("lineEdit_fluidContainer")
        self.lineEdit_startTime = QtGui.QLineEdit(ProjectDetailsView)
        self.lineEdit_startTime.setGeometry(QtCore.QRect(160, 169, 71, 20))
        self.lineEdit_startTime.setObjectName("lineEdit_startTime")
        self.label_startTime = QtGui.QLabel(ProjectDetailsView)
        self.label_startTime.setGeometry(QtCore.QRect(160, 148, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_startTime.setFont(font)
        self.label_startTime.setObjectName("label_startTime")
        self.label_endTime = QtGui.QLabel(ProjectDetailsView)
        self.label_endTime.setGeometry(QtCore.QRect(250, 148, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_endTime.setFont(font)
        self.label_endTime.setObjectName("label_endTime")
        self.lineEdit_endTime = QtGui.QLineEdit(ProjectDetailsView)
        self.lineEdit_endTime.setGeometry(QtCore.QRect(250, 168, 70, 20))
        self.lineEdit_endTime.setObjectName("lineEdit_endTime")
        self.line_2 = QtGui.QFrame(ProjectDetailsView)
        self.line_2.setGeometry(QtCore.QRect(20, 239, 300, 1))
        self.line_2.setStyleSheet("QFrame[frameShape=\"5\"] /* QFrame::VLine == 0x0005 */\n"
"{\n"
"    color: green;\n"
"}")
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_loadSimulation = QtGui.QLabel(ProjectDetailsView)
        self.label_loadSimulation.setGeometry(QtCore.QRect(20, 208, 251, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_loadSimulation.setFont(font)
        self.label_loadSimulation.setStyleSheet("")
        self.label_loadSimulation.setObjectName("label_loadSimulation")
        self.label_preview = QtGui.QLabel(ProjectDetailsView)
        self.label_preview.setGeometry(QtCore.QRect(20, 378, 271, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.label_preview.setFont(font)
        self.label_preview.setStyleSheet("")
        self.label_preview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_preview.setObjectName("label_preview")
        self.line_3 = QtGui.QFrame(ProjectDetailsView)
        self.line_3.setGeometry(QtCore.QRect(20, 409, 300, 1))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_moviePreview = QtGui.QLabel(ProjectDetailsView)
        self.label_moviePreview.setGeometry(QtCore.QRect(20, 425, 300, 200))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_moviePreview.setFont(font)
        self.label_moviePreview.setAutoFillBackground(False)
        self.label_moviePreview.setStyleSheet("QLabel { background-color : green; color : black; };")
        self.label_moviePreview.setText("")
        self.label_moviePreview.setObjectName("label_moviePreview")
        self.pushButton_exploreSimulations = QtGui.QPushButton(ProjectDetailsView)
        self.pushButton_exploreSimulations.setGeometry(QtCore.QRect(20, 341, 301, 23))
        self.pushButton_exploreSimulations.setText("Explore Simulations  ...")
        self.pushButton_exploreSimulations.setObjectName("pushButton_exploreSimulations")
        self.pushButton_help = QtGui.QPushButton(ProjectDetailsView)
        self.pushButton_help.setGeometry(QtCore.QRect(300, 211, 24, 24))
        self.pushButton_help.setText("")
        self.pushButton_help.setObjectName("pushButton_help")
        self.label_fluidContainer_2 = QtGui.QLabel(ProjectDetailsView)
        self.label_fluidContainer_2.setGeometry(QtCore.QRect(21, 313, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_fluidContainer_2.setFont(font)
        self.label_fluidContainer_2.setObjectName("label_fluidContainer_2")

        self.retranslateUi(ProjectDetailsView)
        QtCore.QMetaObject.connectSlotsByName(ProjectDetailsView)

    def retranslateUi(self, ProjectDetailsView):
        ProjectDetailsView.setWindowTitle(QtGui.QApplication.translate("ProjectDetailsView", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_projectName.setText(QtGui.QApplication.translate("ProjectDetailsView", "Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_applyCache.setText(QtGui.QApplication.translate("ProjectDetailsView", "Attach Cache", None, QtGui.QApplication.UnicodeUTF8))
        self.label_detailsView.setText(QtGui.QApplication.translate("ProjectDetailsView", "Simulation Details", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_showPreview.setText(QtGui.QApplication.translate("ProjectDetailsView", "Show Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_projectPath.setText(QtGui.QApplication.translate("ProjectDetailsView", "Project Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fluidContainer.setText(QtGui.QApplication.translate("ProjectDetailsView", "Fluid Container", None, QtGui.QApplication.UnicodeUTF8))
        self.label_startTime.setText(QtGui.QApplication.translate("ProjectDetailsView", "Start Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_endTime.setText(QtGui.QApplication.translate("ProjectDetailsView", "End Time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_loadSimulation.setText(QtGui.QApplication.translate("ProjectDetailsView", "Load Simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_preview.setText(QtGui.QApplication.translate("ProjectDetailsView", "Simulation Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fluidContainer_2.setText(QtGui.QApplication.translate("ProjectDetailsView", "File: -", None, QtGui.QApplication.UnicodeUTF8))

